.buildkite/pipeline.yml
.buildkite/template.yml
LICENSE.md
README.md
package.json

Backports new license and package name to legacy version of the library.
The intention is to provide access to the legacy code, if required by our customers.

chore(release): v0.8.2

---

CHANGELOG.md
README.md
package-lock.json
package.json

Also bumps the version for the next release

fix: correct licensing issues + other tweaks

---

lib/utils/logger.js
package-lock.json
package.json

A review of the code indicates that no other parts are affected by the breaking changes in the library update.

chore: update winston to version 3.

---

package-lock.json
package.json

Removes all vulnerabilities captured by `npm audit` and Github.

chore: fix security vulnerabilities

---

lib/api.js
lib/context.js
lib/resources/custom-categories.js
lib/resources/items.js
lib/resources/orders.js
lib/resources/programs.js
lib/resources/rewards.js

These changes eliminate end-user (developer) confusion as a result of the callback param names.

docs: improve API request callback param names in JSDocs

---

.buildkite/pipeline.yml
.buildkite/template.yml
CHANGELOG.md
LICENSE.md
README.md
lib/api.js
lib/auth.js
lib/config.js
lib/context.js
lib/emitter.js
lib/resources/custom-categories.js
lib/resources/items.js
lib/resources/order-recipients.js
lib/resources/orders.js
lib/resources/programs.js
lib/resources/rewards.js
lib/rewardops.js
lib/schemas/store-order-recipient.js
lib/urls.js
lib/utils/auth.js
lib/utils/logger.js
package-lock.json
package.json
test/config.test.js
test/context.test.js
test/resources/v5/order-recipients.test.js
test/rewardops.test.js

Ticket: https://rewardops.atlassian.net/browse/MX-986

Feature/MX-986 Add PII Endpoints

---

README.md
examples/.gitignore
examples/README.md
examples/config.example.json
examples/create-order-with-pii.js
examples/payloads.example.json

A quick example script for developer users. We'll add more in future.

docs: add `examples` dir with create order PII example [MX-1107]

---

lib/auth.js
lib/schemas/store-order-recipient.js
test/schemas/store-order-recipient.test.js

https://rewardops.atlassian.net/browse/MX-1136
- update the `storeOrderRecipientSchema` to allow UUIDs for the id field.

fix: allow id to be UUID

---

lib/config.js
test/config.test.js

Completes [MX-1239](https://rewardops.atlassian.net/browse/MX-1239)

fix(config): fall back on defaults if `init` given nil prop values

---

lib/resources/orders.js
lib/schemas/cancel-order.js
package-lock.json
test/resources/v4/program-orders.test.js

https://rewardops.atlassian.net/browse/MX-1339
- Added a new function to cancel orders.
- Added unit tests for the new function.
The function was tested on the MX project.

feat: add new cancelOrders function MX-1339

---

CHANGELOG.md
README.md
package-lock.json
package.json

Updates publication instructions

chore(release): 2.4.1

---

index.d.ts
lib/api.js
lib/auth.js
lib/resources/order-recipients.js
lib/utils/logger.js
package-lock.json
package.json
test/utils/logger.test.js

feat: filter sensitive data from logs MX-1252

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.5.1

---

lib/schemas/store-order-recipient.js
package-lock.json
package.json
test/schemas/store-order-recipient.test.js

Allows for memberIds to be strings

chore: update memberId schema to allow for strings

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.5.3

---

CHANGELOG.md
package-lock.json
package.json

This reverts commit e3ca37aa79ae9dd3755323252a963cc0e8d17ec1, reversing changes made to 3d6f8fb8d03bb4cec76fc7d7cc07227c393eaf54.

Revert "Merge pull request #98 from rewardops/release/v2.5.3"

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.7.0

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.7.1

---

index.d.ts
lib/resources/programs.js
lib/resources/subsegments.js
test/resources/v5/subsegments.test.js

**DON'T REMOVE MX-3574 BRANCH**
https://rewardops.atlassian.net/browse/MX-3574
This PR extends sdk with the following methods:
- get subsegment data for a program
**Example of a new method calling from SDK:** 
```
program.subsegments.getAll((...) => {...});
```

[DON'T MERGE] refactor: implemented the base logic to get subsegments (MX-3574)

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.7.2

---

lib/resources/members.js
test/resources/v5/members.test.js

https://rewardops.atlassian.net/browse/MX-3892
Linked PR (could be merged independently):
https://github.com/rewardops/mx/pull/3154

MX-3892: Rename getCart method to getCartSummary
